### PR TITLE
fix: trim sql row to remove leading whitespace or newline

### LINKED ISSUE #235: Bug: sqlite introspection does not detect autoincrement column when sql contains newlines
```typescript
const autoIncrementCol = createSql[0]?.sql
      ?.split(/[\(\),]/)
      ?.find((it) => it.toLowerCase().includes('autoincrement'))
      ?.split(/\s+/)?.[0]
      ?.replace(/["`]/g, '')
```
https://github.com/koskimas/kysely/blob/2c49bae555505d347e73ded4cafc0f5dc7279426/src/dialect/sqlite/sqlite-introspector.ts#L68:L72

given the following sql:
```sql
CREATE TABLE "users"
(
    "id"         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name"       TEXT     NOT NULL
)
```

the result of find the autoincrement row is:   `\n    "id"         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT` 
after split on `whitespace` the first item inside the array is `""` instead of `""id""`

### PR DESCRIPTION
**Pull request by tobiasfoerg**
Fixes #235

### CODE REVIEW

File: src/dialect/sqlite/sqlite-introspector.ts [hunk 1]
```diff
@@ -68,6 +68,7 @@ export class SqliteIntrospector implements DatabaseIntrospector {
     const autoIncrementCol = createSql[0]?.sql
       ?.split(/[\(\),]/)
       ?.find((it) => it.toLowerCase().includes('autoincrement'))
+        ?.trimStart()
```
Comment (koskimas) [inline src/dialect/sqlite/sqlite-introspector.ts:71]: Wrong indentation level

**Comment by koskimas** [comment]
Thanks! Fix the indentation and this is good to go

File: src/dialect/sqlite/sqlite-introspector.ts (hunk 1 above)
Comment (tobiasfoerg) [reply src/dialect/sqlite/sqlite-introspector.ts]: done
